export default {
    id:"it-0",
    family:true,
    label:"Italic",
    link:"https://en.wikipedia.org/wiki/Italic_languages",
    children:[
        {
            id:"it-1",
            label:"Latino-Faliscan",
            link:"https://en.wikipedia.org/wiki/Latino-Faliscan_languages",
            family:true,
            children:[
                {
                    id:"it-3",
                    label:"Faliscan",
                    link:"https://en.wikipedia.org/wiki/Faliscan_language",
                    extinct:true
                },
                {
                    id:"it-4",
                    label:"Latin",
                    link:"https://en.wikipedia.org/wiki/Latin",
                    extinct:true,
                    children:[
                        {
                            id:"it-5",
                            label:"Classical Latin",
                            link:"https://en.wikipedia.org/wiki/Classical_Latin",
                            extinct:true,
                            children:[
                                {
                                    id:"it-6",
                                    label:"Church Latin",
                                    link:"https://en.wikipedia.org/wiki/Ecclesiastical_Latin"
                                }
                            ]
                        },
                        {
                            id:"it-7",
                            label:"Vulgar Latin",
                            link:"https://en.wikipedia.org/wiki/Vulgar_Latin",
                            extinct:true,
                            children:[
                                {
                                    id:"it-8",
                                    label:"Romance",
                                    link:"https://en.wikipedia.org/wiki/Romance_languages",
                                    family:true,
                                    children:[
                                        {
                                            id:"it-9",
                                            label:"Sardinian",
                                            link:"https://en.wikipedia.org/wiki/Sardinian_language"
                                        },
                                        {
                                            id:"it-10",
                                            label:"Logudorese",
                                            link:"https://en.wikipedia.org/wiki/Logudorese_Sardinian"
                                        },
                                        {
                                            id:"it-11",
                                            label:"Campidanese",
                                            link:"https://en.wikipedia.org/wiki/Campidanese_Sardinian"
                                        },
                                        {
                                            id:"it-12",
                                            label:"Eastern",
                                            family:true,
                                            link:"https://en.wikipedia.org/wiki/Balkan_Romance_languages",
                                            children:[
                                                {
                                                    id:"it-13",
                                                    label:"Aromanian",
                                                    link:"https://en.wikipedia.org/wiki/Aromanian_language"
                                                },
                                                {
                                                    id:"it-14",
                                                    label:"Istro-Romanian",
                                                    link:"https://en.wikipedia.org/wiki/Istro-Romanian_language"
                                                },
                                                {
                                                    id:"it-15",
                                                    label:"Megleno-Romanian",
                                                    link:"https://en.wikipedia.org/wiki/Megleno-Romanian_language"
                                                },
                                                {
                                                    id:"it-16",
                                                    label:"Romanian",
                                                    link:"https://en.wikipedia.org/wiki/Romanian_language"
                                                }
                                            ]
                                        },
                                        {
                                            id:"it-17",
                                            label:"Italo-Western",
                                            link:"https://en.wikipedia.org/wiki/Italo-Western_languages",
                                            family:true,
                                            children:[
                                                {
                                                    id:"it-18",
                                                    label:"Gallo-Iberian",
                                                    link:"https://en.wikipedia.org/wiki/Western_Romance_languages",
                                                    family:true,
                                                    children:[
                                                        {
                                                            id:"it-19",
                                                            label:"Iberian",
                                                            link:"https://en.wikipedia.org/wiki/Iberian_Romance_languages",
                                                            family:true,
                                                            children:[
                                                                {
                                                                    id:"it-20",
                                                                    label:"Aragonese",
                                                                    link:"https://en.wikipedia.org/wiki/Aragonese_language"
                                                                },
                                                                {
                                                                    id:"it-21",
                                                                    label:"Astur-Leonese",
                                                                    link:"https://en.wikipedia.org/wiki/Asturleonese_language",
                                                                    extinct:true,
                                                                    children:[
                                                                        {
                                                                            id:"it-22",
                                                                            label:"Asturian",
                                                                            link:'https://en.wikipedia.org/wiki/Asturian_language'
                                                                        },
                                                                        {
                                                                            id:"it-23",
                                                                            label:"Extremaduran",
                                                                            link:"https://en.wikipedia.org/wiki/Extremaduran_language"
                                                                        },
                                                                        {
                                                                            id:"it-24",
                                                                            label:"Leonese",
                                                                            link:"https://en.wikipedia.org/wiki/Leonese_dialect"
                                                                        },
                                                                        {
                                                                            id:"it-25",
                                                                            label:"Mirandese",
                                                                            link:"https://en.wikipedia.org/wiki/Mirandese_language"
                                                                        },
                                                                        {
                                                                            id:"it-62",
                                                                            label:"Cantabrian",
                                                                            link:"https://en.wikipedia.org/wiki/Cantabrian_dialect"
                                                                        }
                                                                    ]
                                                                },
                                                                {
                                                                    id:"it-26",
                                                                    label:"Galician-Portuguese",
                                                                    link:"https://en.wikipedia.org/wiki/Galician-Portuguese",
                                                                    extinct:true,
                                                                    children:[
                                                                        {
                                                                            id:"it-27",
                                                                            label:"Eonavian",
                                                                            link:"https://en.wikipedia.org/wiki/Galician-Asturian"
                                                                        },
                                                                        {
                                                                            id:"it-28",
                                                                            label:"Fala",
                                                                            link:"https://en.wikipedia.org/wiki/Fala_language"
                                                                        },
                                                                        {
                                                                            id:"it-29",
                                                                            label:"Galician",
                                                                            link:"https://en.wikipedia.org/wiki/Galician_language"
                                                                        },
                                                                        {
                                                                            id:"it-30",
                                                                            label:"Portuguese",
                                                                            link:"https://en.wikipedia.org/wiki/Portuguese_language"
                                                                        }
                                                                    ]
                                                                },
                                                                {
                                                                    id:"it-31",
                                                                    label:"Mozarabic",
                                                                    link:"https://en.wikipedia.org/wiki/Andalusi_Romance",
                                                                    extinct:true
                                                                },
                                                                {
                                                                    id:"it-32",
                                                                    label:"Old Spanish",
                                                                    link:"https://en.wikipedia.org/wiki/Old_Spanish",
                                                                    extinct:true,
                                                                    children:[
                                                                        {
                                                                            id:"it-33",
                                                                            label:"Ladino",
                                                                            link:"https://en.wikipedia.org/wiki/Judaeo-Spanish"
                                                                        },
                                                                        {
                                                                            id:"it-34",
                                                                            label:"Spanish",
                                                                            link:"https://en.wikipedia.org/wiki/Spanish_language"
                                                                        }
                                                                    ]
                                                                }
                                                            ]
                                                        },
                                                        {
                                                            id:"it-35",
                                                            label:"Gallo-Romance",
                                                            link:"https://en.wikipedia.org/wiki/Gallo-Romance_languages",
                                                            family:true,
                                                            children:[
                                                                {
                                                                    id:"it-36",
                                                                    label:"Cisalpine",
                                                                    link:"https://en.wikipedia.org/wiki/Gallo-Italic_languages",
                                                                    family:true,
                                                                    children:[
                                                                        {
                                                                            id:"it-37",
                                                                            label:"Emilian",
                                                                            link:"https://en.wikipedia.org/wiki/Emilian_dialects"
                                                                        },
                                                                        {
                                                                            id:"it-38",
                                                                            label:"Ligurian",
                                                                            link:"https://en.wikipedia.org/wiki/Ligurian_language"
                                                                        },
                                                                        {
                                                                            id:"it-39",
                                                                            label:"Lombard",
                                                                            link:"https://en.wikipedia.org/wiki/Lombard_language"
                                                                        },
                                                                        {
                                                                            id:"it-40",
                                                                            label:"Piedmontese",
                                                                            link:"https://en.wikipedia.org/wiki/Piedmontese_language"
                                                                        },
                                                                        {
                                                                            id:"it-41",
                                                                            label:"Venetian",
                                                                            link:"https://en.wikipedia.org/wiki/Venetian_language"
                                                                        }
                                                                    ]
                                                                },
                                                                {
                                                                    id:"it-42",
                                                                    label:"Langue d'Oïl",
                                                                    link:"https://en.wikipedia.org/wiki/Langues_d%27o%C3%AFl",
                                                                    family:true,
                                                                    children:[
                                                                        {
                                                                            id:"it-43",
                                                                            label:"French",
                                                                            link:"https://en.wikipedia.org/wiki/French_language"
                                                                        },
                                                                        {
                                                                            id:"it-44",
                                                                            label:"Gallo",
                                                                            link:"https://en.wikipedia.org/wiki/Gallo_language"
                                                                        },
                                                                        {
                                                                            id:"it-45",
                                                                            label:"Norman",
                                                                            link:"https://en.wikipedia.org/wiki/Norman_language"
                                                                        },
                                                                        {
                                                                            id:"it-46",
                                                                            label:"Walloon",
                                                                            link:"https://en.wikipedia.org/wiki/Walloon_language"
                                                                        }
                                                                    ]
                                                                },
                                                                {
                                                                    id:"it-47",
                                                                    label:"Occitan",
                                                                    link:"https://en.wikipedia.org/wiki/Occitano-Romance_languages",
                                                                    family:true,
                                                                    children:[
                                                                        {
                                                                            id:"it-48",
                                                                            label:"Catalan",
                                                                            link:"https://en.wikipedia.org/wiki/Catalan_language"
                                                                        },
                                                                        {
                                                                            id:"it-49",
                                                                            label:"Occitan",
                                                                            link:"https://en.wikipedia.org/wiki/Occitan_language",
                                                                        }
                                                                    ]
                                                                },
                                                                {
                                                                    id:"it-50",
                                                                    label:"Rhaetian",
                                                                    link:"https://en.wikipedia.org/wiki/Rhaeto-Romance_languages",
                                                                    extinct:true,
                                                                    children:[
                                                                        {
                                                                            id:"it-51",
                                                                            label:"Friulian",
                                                                            link:"https://en.wikipedia.org/wiki/Friulian_language"
                                                                        },
                                                                        {
                                                                            id:"it-52",
                                                                            label:"Ladin",
                                                                            link:"https://en.wikipedia.org/wiki/Ladin_language"
                                                                        },
                                                                        {
                                                                            id:"it-53",
                                                                            label:"Romansh",
                                                                            link:"https://en.wikipedia.org/wiki/Romansh_language"
                                                                        }
                                                                    ]
                                                                }
                                                            ]
                                                        }
                                                    ]
                                                },
                                                {
                                                    id:"it-54",
                                                    label:"Italo-Dalmatian",
                                                    link:"https://en.wikipedia.org/wiki/Italo-Dalmatian_languages",
                                                    family:true,
                                                    children:[
                                                        {
                                                            id:"it-55",
                                                            label:"Corsican",
                                                            link:"https://en.wikipedia.org/wiki/Corsican_language"
                                                        },
                                                        {
                                                            id:"it-56",
                                                            label:"Dalmatian",
                                                            extinct:true,
                                                            link:"https://en.wikipedia.org/wiki/Dalmatian_language"
                                                        },
                                                        {
                                                            id:"it-57",
                                                            label:"Istriot",
                                                            link:"https://en.wikipedia.org/wiki/Istriot_language"
                                                        },
                                                        {
                                                            id:"it-58",
                                                            label:"Italian",
                                                            link:"https://en.wikipedia.org/wiki/Italian_language"
                                                        },
                                                        {
                                                            id:"it-59",
                                                            label:"Neapolitan",
                                                            link:"https://en.wikipedia.org/wiki/Neapolitan_language"
                                                        },
                                                        {
                                                            id:"it-60",
                                                            label:"Sassarese",
                                                            link:"https://en.wikipedia.org/wiki/Sassarese_language"
                                                        },
                                                        {
                                                            id:"it-61",
                                                            label:"Sicilian",
                                                            link:"https://en.wikipedia.org/wiki/Sicilian_language"
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}
